### ISSUE TITLE
Default dataset "airbnb_data" isn't importing

### ISSUE THREAD

**Issue by ElijousGit** [nhemerson/mako-bi#14]
On a fresh clone, the default "airbnb_data" dataset isn't present. This is probably due to the "airbnb_data" being listed in the gitignore file.

What should happen is that the "airbnb_data" dataset should be imported into the data file when the repo is cloned

**Comment by nhemerson** [comment]
I will fix this tomorrow May 17

**Comment by nhemerson** [comment]
This has been fixed. Need a fresh clone to test @ElijousGit
