### ISSUE TITLE
Needs a requirements.txt

### ISSUE THREAD

**Issue by nhemerson** [nhemerson/mako-bi#6]
This file has all required libraries and library version for the app to run and is necessary to launch Docker.

Perplexity explanation of a requirements.txt here:

https://www.perplexity.ai/search/Explain-to-me-BEpDFefwTQi8gIw3p5L5dQ#0

**Comment by ElijousGit** [comment]
Shooting for end of day today

**Comment by ElijousGit** [comment]
Are there specific packages that the Docker needs? (not just the packages for the app to run)

**Comment by nhemerson** [comment]
We don't add the actual python version to the file. But we can suggest to people what version of Python to use for best performance. That can be done in the README

**Comment by ElijousGit** [comment]
Resolved in this commit: https://github.com/nhemerson/mako-bi/commit/6160a54a09ae4ac73149b939f407bafad23c7644
